apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-app
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30080
    name: http
  type: NodePort
